name: quiz_rally
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.4
  cloud_functions: ^4.6.5
  collection: ^1.18.0
  firebase_analytics: ^10.8.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_crashlytics: ^3.4.14
  firebase_storage: ^11.7.2
  flutter_easyloading: ^3.0.5
  flutter_gen_runner: ^5.4.0
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.10
  image: ^4.1.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  riverpod: ^2.5.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  google_sign_in: ^5.4.4
  go_router: ^6.0.6
  image_picker_web: ^3.0.0+1
  cupertino_icons: ^1.0.8
  json_serializable: ^6.9.5
  universal_image: ^1.0.10

dev_dependencies:
  freezed: ^2.4.6
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
